version: '3.1'

services:

  mysql: #servicio mysql
    image: mysql:8.0 #imagen
    container_name: mysql-contenedorcrud #nombre contenedor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3006:3006
    networks:
      - my_network #una red del contenedor de la aplicacion

 
    
volumes:
  mysql-volume:

networks:
  my_network: